# Generated by Django 4.1.1 on 2022-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('profile_pic', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('wishlist', models.BooleanField(blank=True, default=False, null=True)),
                ('cartlist', models.BooleanField(blank=True, default=False, null=True)),
                ('old_price', models.FloatField(blank=True, max_length=200, null=True)),
                ('new_price', models.FloatField(blank=True, max_length=200, null=True)),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('refund', models.BooleanField(blank=True, default=True, null=True)),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('features', models.CharField(blank=True, max_length=200, null=True)),
                ('specifications', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
